# Site settings
title: Twofish recipes
email: rachel@twofishcreative.com
description: > # this means to ignore newlines until "baseurl:"
  Recipes for food we make.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://twofishcreative.com" # the base hostname & protocol for your site
twitter_username: racheltwofish
github_username:  racheltwofish

# Build settings
markdown: kramdown
